import Image from "next/image";
import Link from "next/link";
import type { Locale } from "@/lib/types";
import { companyContact, copy, getPath } from "@/lib/content";
import { Arrow } from "./Icons";
import { ContactCta } from "./Footer";
import { ContactForm } from "./ContactForm";

export type SectionKey = "company" | "production" | "boards" | "edges" | "gallery" | "documents" | "contact";

const titles: Record<SectionKey, { tr: string; en: string; intro: { tr: string; en: string } }> = {
  company:{tr:"1993'ten beri ahşap kaplama ve panel üretimi.",en:"Wood veneer and panel production since 1993.",intro:{tr:"Çalışırlar; doğal ve endüstriyel kaplama, kaplamalı panel ve ahşap kenar bandı ürünleriyle yurtiçi ve uluslararası projelere hizmet verir.",en:"Çalışırlar supplies natural and industrial veneers, veneered panels and wood edge bands for domestic and international projects."}},
  production:{tr:"Tutarlı yüzey için kontrollü üretim.",en:"Controlled production for consistent surfaces.",intro:{tr:"Torbalı, İzmir'deki yaklaşık 11.000 m² tesiste yüzey seçimi, panel hazırlığı ve kaplama uygulaması uzman süreç kontrolüyle yönetilir.",en:"Surface selection, panel preparation and veneering are managed with expert process control at the approximately 11,000 m² Torbalı facility."}},
  boards:{tr:"Mimari yüzeyler için kaplamalı panel çözümleri.",en:"Veneered panel solutions for architectural surfaces.",intro:{tr:"Doğal veya endüstriyel kaplama seçenekleriyle, mobilya ve iç mekân projelerine göre üretilen MDF ve sunta çözümleri.",en:"MDF and chipboard solutions produced for furniture and interior projects with natural or industrial veneer options."}},
  edges:{tr:"Ahşap kenar bandı seçenekleri.",en:"Wood edge band options.",intro:{tr:"Doğal ve endüstriyel kaplamalarla uyumlu tutkallı veya tela destekli ahşap kenar bantları.",en:"Pre-glued or fleece-backed wood edge bands matched to natural and industrial veneers."}},
  gallery:{tr:"Ürün ve uygulama görselleri.",en:"Product and application images.",intro:{tr:"Doğal, egzotik ve endüstriyel kaplamaların damar, ton ve doku ayrıntılarını inceleyin.",en:"View grain, tone and texture details of natural, exotic and industrial veneers."}},
  documents:{tr:"Kurumsal belgeler.",en:"Corporate documents.",intro:{tr:"Çalışırlar'ın kurumsal, marka ve kalite belgeleri.",en:"Çalışırlar corporate, brand and quality documents."}},
  contact:{tr:"Numune ve proje talebi.",en:"Sample and project enquiry.",intro:{tr:"Malzeme seçimi, ürün bilgisi, numune, stok ve proje talepleriniz için ekibimizle iletişime geçin.",en:"Contact our team for material selection, product information, samples, availability and project enquiries."}}
};

function Hero({ locale, type }: { locale: Locale; type: SectionKey }) { const item=titles[type]; const visual=type === "company" ? "/images/campaign/forest-interlude.jpg" : type === "production" ? "/materials/industrial/cls-03-hareli-mese/catalog.jpg" : type === "boards" ? "/images/editorial/web-icin4.jpg" : type === "edges" ? "/images/editorial/bandbanner2.jpg" : null; const productFamily=type === "boards" || type === "edges"; return <section className={`page-hero ${type === "production" ? "dark" : ""} ${visual ? "has-image" : ""}`}>{visual&&<Image src={visual} alt="" fill priority sizes="100vw"/>}<div className="page-hero-content"><div className="breadcrumbs"><Link href={getPath(locale,"home")}>{locale === "tr" ? "Ana Sayfa" : "Home"}</Link> / {productFamily&&<><Link href={getPath(locale,"products")}>{locale === "tr" ? "Ürünler" : "Products"}</Link> / </>}{item[locale]}</div><span className="eyebrow">ÇALIŞIRLAR · {copy[locale].nav[productFamily ? "products" : type === "company" ? "company" : type]}</span><h1>{item[locale]}</h1><p>{item.intro[locale]}</p></div></section>; }

export function SectionPage({ locale, type }: { locale: Locale; type: SectionKey }) { return <main><Hero locale={locale} type={type}/>{type === "company" && <Company locale={locale}/>} {type === "production" && <Production locale={locale}/>} {type === "boards" && <Boards locale={locale}/>} {type === "edges" && <Edges locale={locale}/>} {type === "gallery" && <Gallery locale={locale}/>} {type === "documents" && <Documents locale={locale}/>} {type === "contact" && <Contact locale={locale}/>} {type !== "contact" && <ContactCta locale={locale}/>}</main>; }

function Company({locale}:{locale:Locale}) { const tr=locale==="tr"; const rows=tr ? [["1993","Doğal ve endüstriyel ahşap kaplama ürünlerinin sunulmaya başlanması."],["2007","Torbalı, İzmir'de üretim tesisinin kurulması."],["Ürünler","Kaplamalı panel ve ahşap kenar bandı ürünlerinin eklenmesi."],["Bugün","Dört ürün grubuyla yurtiçi ve uluslararası projelere hizmet."]] : [["1993","Launch of natural and industrial wood veneer products."],["2007","Establishment of the production facility in Torbalı, İzmir."],["Products","Addition of veneered panels and wood edge bands."],["Today","Supplying domestic and international projects across four product groups."]]; return <section className="editorial"><div className="editorial-grid"><span className="eyebrow">01 — {tr?"ŞİRKET BİLGİSİ":"COMPANY INFORMATION"}</span><div><h2>{tr?"1993'ten beri ahşap kaplama ve panel üretimi.":"Wood veneer and panel production since 1993."}</h2><div className="rich-copy"><p>{tr?"Çalışırlar Orman Ürünleri, kaplama ve kereste ticareti deneyimiyle 1993'ten beri doğal ve endüstriyel ahşap kaplama ürünleri sunar.":"Çalışırlar Wood Products has supplied natural and industrial wood veneer products since 1993, building on experience in veneer and timber trading."}</p><p>{tr?"Şirket; malzeme seçimi, kaplamalı panel üretimi ve proje desteği hizmetlerini Torbalı'daki üretim tesisi üzerinden yürütür.":"The company provides material selection, veneered panel production and project support through its Torbalı production facility."}</p><Image className="company-brand-signature" src="/images/brand/calisirlar-logo-lockup.png" alt="Çalışırlar Orman Ürünleri" width={1100} height={815}/></div></div></div><div className="timeline">{rows.map(([year,text])=><article key={year}><strong>{year}</strong><div><h3>{text}</h3></div></article>)}</div></section>; }
function Production({locale}:{locale:Locale}) { const tr=locale==="tr"; const steps=tr?["Kaplama ve malzeme seçimi","Panel hazırlığı","Kaplama uygulaması","Süreç kontrolü","Bitmiş yüzey"]:["Veneer and material selection","Panel preparation","Veneering","Process control","Finished surface"];return <section className="editorial"><div className="editorial-grid"><span className="eyebrow">11.000 m² · TORBALI</span><div><h2>{tr?"Kaplamalı panel üretimi ve süreç kontrolü.":"Veneered panel production and process control."}</h2><div className="rich-copy"><p>{tr?"2007 yılında kurulan Torbalı tesisi, doğal ve endüstriyel kaplamalı MDF ile yonga levha üretimi için yaklaşık 11.000 m²'lik bir üretim alanı sunar.":"Established in 2007, the Torbalı facility provides approximately 11,000 m² for natural and industrial veneered MDF and chipboard production."}</p><p>{tr?"Malzeme seçimi, panel hazırlığı, kaplama uygulaması ve bitmiş yüzey kontrolü aynı tesiste yürütülür.":"Material selection, panel preparation, veneering and finished-surface control are carried out at the same facility."}</p></div></div></div><div className="cards-3">{steps.map((step,index)=><article className="info-card" key={step}><span className="eyebrow">0{index+1}</span><h3>{step}</h3></article>)}</div></section>; }
function Boards({locale}:{locale:Locale}) {const tr=locale==="tr";return <section className="editorial"><div className="editorial-grid"><span className="eyebrow">{tr?"TEKNİK BİLGİ":"TECHNICAL DATA"}</span><div><h2>{tr?"Kaplamalı MDF ve sunta ölçüleri.":"Veneered MDF and chipboard dimensions."}</h2><p>{tr?"MDF ve yonga levha paneller, doğal veya endüstriyel kaplama koleksiyonundan seçilen yüzeylerle proje gereksinimlerine göre üretilebilir.":"MDF and chipboard panels can be produced to project requirements with surfaces selected from the natural or industrial veneer collections."}</p><dl className="spec-table"><div><dt>{tr?"Standart ölçü":"Standard size"}</dt><dd>210 × 280 cm</dd></div><div><dt>{tr?"Kalınlıklar":"Thicknesses"}</dt><dd>4, 6, 8, 10, 12, 16, 17, 18, 22, 25, 30 mm</dd></div><div><dt>{tr?"3 mm levha":"3 mm board"}</dt><dd>170 × 210 cm</dd></div><div><dt>{tr?"Talebe bağlı ölçüler":"On-request sizes"}</dt><dd>183 × 366 cm · 210 × 366 cm</dd></div></dl><p className="form-note">{tr?"Yüzey, arkalık ve özel ölçü seçenekleri proje detaylarına göre belirlenir.":"Face, backing and custom-size options are confirmed according to project requirements."}</p></div></div></section>}
function Edges({locale}:{locale:Locale}){const tr=locale==="tr";return <section className="editorial"><div className="editorial-grid"><span className="eyebrow">{tr?"TEKNİK BİLGİ":"TECHNICAL DATA"}</span><div><h2>{tr?"Tutkallı ve tela destekli kenar bantları.":"Pre-glued and fleece-backed edge bands."}</h2><p>{tr?"Kök desenler hariç doğal ve endüstriyel kaplamalardan üretilen kenar bantları panel yüzeyiyle uyumlu şekilde hazırlanır.":"Edge bands produced from natural and industrial veneers, excluding burls, are prepared to match the panel surface."}</p><dl className="spec-table"><div><dt>{tr?"Standart genişlik":"Standard width"}</dt><dd>22 mm · 45 mm</dd></div><div><dt>{tr?"Tela destekli rulo":"Fleece-backed roll"}</dt><dd>100 m</dd></div><div><dt>{tr?"Tutkallı rulo":"Pre-glued roll"}</dt><dd>50 m</dd></div><div><dt>{tr?"Talebe bağlı genişlik":"On-request width"}</dt><dd>12–200 mm</dd></div></dl></div></div></section>}
const galleryImages=["/images/products/AFRAMOSIA.jpg","/images/products/usa_ceviz.jpg","/images/products/zebranoo.jpg","/materials/industrial/cls-03-hareli-mese/catalog.jpg","/materials/industrial/cls-25-gri-kok/catalog.jpg","/images/products/Dogal-Teak.jpg","/materials/industrial/cls-39-fume-mese/catalog.jpg"];
function Gallery({locale}:{locale:Locale}){const tr=locale==="tr";return <section className="editorial"><div className="section-head"><div><span className="eyebrow">{tr?"ÜRÜN GÖRSELLERİ":"PRODUCT IMAGES"}</span><h2>{tr?"Kaplama yüzey detayları.":"Veneer surface details."}</h2></div><p>{tr?"Çalışırlar ürün kataloğundaki doğal, egzotik ve endüstriyel kaplama görsellerini inceleyin.":"View natural, exotic and industrial veneer images from the Çalışırlar product catalogue."}</p></div><div className="gallery-grid">{galleryImages.map((image,index)=><div className="gallery-item" key={image}><Image src={image} fill sizes="(max-width:760px) 100vw, 60vw" alt={`${tr?"Çalışırlar ahşap yüzey kataloğu":"Çalışırlar wood surface catalogue"} ${index+1}`}/><span>{tr?"Malzeme":"Material"} 0{index+1}</span></div>)}</div></section>}
function Documents({locale}:{locale:Locale}){const tr=locale==="tr";const docs=tr?[["Kurumsal Takdir","İzmir ticaret ve vergi performansına ilişkin belge"],["Sanayi Başarısı","Ege Bölgesi Sanayi Odası"],["Marka & Kalite","Türk Patent ve kalite yönetimi referansları"]]:[["Corporate Recognition","İzmir trade and tax performance document"],["Industrial Achievement","Aegean Region Chamber of Industry"],["Brand & Quality","Turkish Patent and quality-management references"]];return <section className="editorial"><div className="cards-3">{docs.map(([title,body],index)=><article className="info-card" key={title}><span className="eyebrow">0{index+1}</span><div><h3>{title}</h3><p>{body}</p></div><span className="form-note">{tr?"Belge kopyaları ve güncel geçerlilik bilgileri talep halinde paylaşılır.":"Document copies and current validity information are available on request."}</span></article>)}</div></section>}
function Contact({locale}:{locale:Locale}){const tr=locale==="tr";return <section className="editorial"><div className="contact-grid"><div className="contact-details"><section><span className="eyebrow">{tr?"MERKEZ OFİS":"HEAD OFFICE"}</span><h3>Çalışırlar Orman Ürünleri</h3><p>{companyContact.headOffice}</p>{companyContact.headPhones.map(p=><a key={p} href={`tel:${p.replace(/\D/g,"")}`}>{p}</a>)}</section><section><span className="eyebrow">{tr?"FABRİKA":"FACTORY"}</span><h3>Torbalı · İzmir</h3><p>{companyContact.factory}</p>{companyContact.factoryPhones.map(p=><a key={p} href={`tel:${p.replace(/\D/g,"").slice(0,12)}`}>{p}</a>)}</section><a className="text-link" href={`mailto:${companyContact.email}`}>{companyContact.email}<Arrow/></a></div><ContactForm locale={locale}/></div></section>}
