import Image from "next/image";
import Link from "next/link";
import type { Locale } from "@/lib/types";
import { companyContact, copy, getPath } from "@/lib/content";
import { Arrow } from "./Icons";
import { ContactCta } from "./Footer";
import { ContactForm } from "./ContactForm";

export type SectionKey = "company" | "production" | "boards" | "edges" | "gallery" | "documents" | "contact";

const titles: Record<SectionKey, { tr: string; en: string; intro: { tr: string; en: string } }> = {
  company:{tr:"Malzemeyi tanıyan birikim. Üretimi yöneten disiplin.",en:"Material knowledge. Production discipline.",intro:{tr:"1993'ten bugüne uzanan ahşap yüzey uzmanlığı; modern üretim kabiliyeti ve uzun vadeli iş ortaklığı yaklaşımıyla gelişmeye devam ediyor.",en:"Wood-surface expertise dating back to 1993 continues to evolve through modern production capability and a long-term partnership approach."}},
  production:{tr:"Tutarlı yüzey için kontrollü üretim.",en:"Controlled production for consistent surfaces.",intro:{tr:"Torbalı, İzmir'deki yaklaşık 11.000 m² tesiste yüzey seçimi, panel hazırlığı ve kaplama uygulaması uzman süreç kontrolüyle yönetilir.",en:"Surface selection, panel preparation and veneering are managed with expert process control at the approximately 11,000 m² Torbalı facility."}},
  boards:{tr:"Mimari yüzeyler için kaplamalı panel çözümleri.",en:"Veneered panel solutions for architectural surfaces.",intro:{tr:"Doğal veya endüstriyel kaplama seçenekleriyle, mobilya ve iç mekân projelerine göre üretilen MDF ve sunta çözümleri.",en:"MDF and chipboard solutions produced for furniture and interior projects with natural or industrial veneer options."}},
  edges:{tr:"Yüzeyi tamamlayan hassas detay.",en:"The precise detail that completes the surface.",intro:{tr:"Doğal ve endüstriyel kaplama koleksiyonlarıyla aynı malzeme dilini taşıyan tutkallı veya tela destekli ahşap kenar bantları.",en:"Glued or fleece-backed wood edge bands carrying the same material language as the natural and industrial veneer collections."}},
  gallery:{tr:"Yüzeyi yakından inceleyin.",en:"Examine the surface up close.",intro:{tr:"Çalışırlar koleksiyonundan seçilen doğal, egzotik ve endüstriyel yüzeylerin damar, ton ve doku ayrıntıları.",en:"Grain, tone and texture details from selected natural, exotic and industrial surfaces in the Çalışırlar collection."}},
  documents:{tr:"Güvenin kurumsal karşılığı.",en:"The corporate evidence behind trust.",intro:{tr:"Çalışırlar'ın kurumsal geçmişine, marka değerine ve kalite yaklaşımına eşlik eden belge arşivi.",en:"An archive supporting Çalışırlar's corporate history, brand value and approach to quality."}},
  contact:{tr:"Projeniz için doğru yüzeyi birlikte netleştirelim.",en:"Let’s define the right surface for your project.",intro:{tr:"Malzeme seçimi, ürün detayları ve proje talepleriniz için uzman ekibimizle iletişime geçin.",en:"Contact our team for material selection, product details and project enquiries."}}
};

function Hero({ locale, type }: { locale: Locale; type: SectionKey }) { const item=titles[type]; const visual=type === "company" ? "/images/campaign/forest-interlude.jpg" : type === "production" ? "/images/products/a3_harelimese.jpg" : type === "boards" ? "/images/editorial/web-icin4.jpg" : type === "edges" ? "/images/editorial/bandbanner2.jpg" : null; const productFamily=type === "boards" || type === "edges"; return <section className={`page-hero ${type === "production" ? "dark" : ""} ${visual ? "has-image" : ""}`}>{visual&&<Image src={visual} alt="" fill priority sizes="100vw"/>}<div className="page-hero-content"><div className="breadcrumbs"><Link href={getPath(locale,"home")}>{locale === "tr" ? "Ana Sayfa" : "Home"}</Link> / {productFamily&&<><Link href={getPath(locale,"products")}>{locale === "tr" ? "Ürünler" : "Products"}</Link> / </>}{item[locale]}</div><span className="eyebrow">ÇALIŞIRLAR · {copy[locale].nav[productFamily ? "products" : type === "company" ? "company" : type]}</span><h1>{item[locale]}</h1><p>{item.intro[locale]}</p></div></section>; }

export function SectionPage({ locale, type }: { locale: Locale; type: SectionKey }) { return <main><Hero locale={locale} type={type}/>{type === "company" && <Company locale={locale}/>} {type === "production" && <Production locale={locale}/>} {type === "boards" && <Boards locale={locale}/>} {type === "edges" && <Edges locale={locale}/>} {type === "gallery" && <Gallery locale={locale}/>} {type === "documents" && <Documents locale={locale}/>} {type === "contact" && <Contact locale={locale}/>} {type !== "contact" && <ContactCta locale={locale}/>}</main>; }

function Company({locale}:{locale:Locale}) { const tr=locale==="tr"; const rows=tr ? [["1993","Doğal ve endüstriyel ahşap kaplama koleksiyonunun genişlemesi."],["2007","Torbalı, İzmir'de modern üretim tesisinin kurulması."],["Gelişim","Kaplamalı panel ve tamamlayıcı ahşap kenar çözümlerinin geliştirilmesi."],["Bugün","Dört tamamlayıcı ürün ailesiyle yurtiçi ve uluslararası projelere hizmet."]] : [["1993","Expansion of the natural and industrial veneer collection."],["2007","Establishment of the modern production facility in Torbalı, İzmir."],["Evolution","Development of veneered panel and coordinated wood-edge solutions."],["Today","Supporting domestic and international projects across four complementary product families."]]; return <section className="editorial"><div className="editorial-grid"><span className="eyebrow">01 — {tr?"UZMANLIK MİRASI":"A LEGACY OF EXPERTISE"}</span><div><h2>{tr?"1993'ten bugüne, ahşap yüzeylerde uzmanlık.":"Wood-surface expertise, from 1993 to today."}</h2><div className="rich-copy"><p>{tr?"Çalışırlar Orman Ürünleri'nin kökleri, nesilden nesile aktarılan kaplama ve kereste ticareti deneyimine dayanır. Bu birikim, 1993'ten itibaren doğal ve endüstriyel ahşap kaplamaları kapsayan güçlü bir yüzey koleksiyonuna dönüştü.":"Çalışırlar Wood Products is rooted in veneer and timber trading experience passed from one generation to the next. Since 1993, this knowledge has developed into a strong collection of natural and industrial wood veneers."}</p><p>{tr?"Bugün malzeme seçimi, kontrollü üretim ve uzun vadeli iş ortaklığı yaklaşımı aynı kalite anlayışında buluşuyor.":"Today, material selection, controlled production and a long-term partnership approach come together under one understanding of quality."}</p><Image className="company-brand-signature" src="/images/brand/calisirlar-logo-lockup.png" alt="Çalışırlar Orman Ürünleri" width={1100} height={815}/></div></div></div><div className="timeline">{rows.map(([year,text])=><article key={year}><strong>{year}</strong><div><h3>{text}</h3></div></article>)}</div></section>; }
function Production({locale}:{locale:Locale}) { const tr=locale==="tr"; const steps=tr?["Kaplama ve malzeme seçimi","Panel hazırlığı","Kaplama uygulaması","Uzman süreç kontrolü","Bitmiş yüzey"]:["Veneer and material selection","Panel preparation","Veneering","Expert process oversight","Finished surface"];return <section className="editorial"><div className="editorial-grid"><span className="eyebrow">11.000 m² · TORBALI</span><div><h2>{tr?"Üretim gücü, uzman süreç kontrolüyle birleşir.":"Production capability, guided by expert process control."}</h2><div className="rich-copy"><p>{tr?"2007 yılında kurulan Torbalı tesisi, doğal ve endüstriyel kaplamalı MDF ile yonga levha üretimi için yaklaşık 11.000 m²'lik bir üretim alanı sunar.":"Established in 2007, the Torbalı facility provides approximately 11,000 m² for natural and industrial veneered MDF and chipboard production."}</p><p>{tr?"Malzeme seçimi, panel hazırlığı, kaplama uygulaması ve bitmiş yüzey kontrolü; tutarlı sonuç hedefiyle aynı üretim kültürü içinde yönetilir.":"Material selection, panel preparation, veneering and finished-surface control are managed within one production culture focused on consistent outcomes."}</p></div></div></div><div className="cards-3">{steps.map((step,index)=><article className="info-card" key={step}><span className="eyebrow">0{index+1}</span><h3>{step}</h3></article>)}</div></section>; }
function Boards({locale}:{locale:Locale}) {const tr=locale==="tr";return <section className="editorial"><div className="editorial-grid"><span className="eyebrow">{tr?"TEKNİK BİLGİ":"TECHNICAL DATA"}</span><div><h2>{tr?"Yüzey seçimi, panel performansıyla buluşur.":"Surface selection meets panel performance."}</h2><p>{tr?"MDF ve yonga levha paneller, doğal veya endüstriyel kaplama koleksiyonundan seçilen yüzeylerle proje gereksinimlerine göre üretilebilir.":"MDF and chipboard panels can be produced to project requirements with surfaces selected from the natural or industrial veneer collections."}</p><dl className="spec-table"><div><dt>{tr?"Standart ölçü":"Standard size"}</dt><dd>210 × 280 cm</dd></div><div><dt>{tr?"Kalınlıklar":"Thicknesses"}</dt><dd>4, 6, 8, 10, 12, 16, 17, 18, 22, 25, 30 mm</dd></div><div><dt>{tr?"3 mm levha":"3 mm board"}</dt><dd>170 × 210 cm</dd></div><div><dt>{tr?"Talebe bağlı ölçüler":"On-request sizes"}</dt><dd>183 × 366 cm · 210 × 366 cm</dd></div></dl><p className="form-note">{tr?"Yüzey, arkalık ve özel ölçü seçenekleri proje detaylarına göre birlikte netleştirilir.":"Face, backing and custom-size options are confirmed according to project requirements."}</p></div></div></section>}
function Edges({locale}:{locale:Locale}){const tr=locale==="tr";return <section className="editorial"><div className="editorial-grid"><span className="eyebrow">{tr?"TAMAMLAYICI DETAY":"COORDINATED DETAIL"}</span><div><h2>{tr?"Aynı malzeme dilini son ayrıntıya taşıyın.":"Carry one material language through to the final detail."}</h2><p>{tr?"Kök desenler hariç doğal ve endüstriyel kaplamalardan üretilen tutkallı veya tela destekli kenar bantları, panel yüzeyiyle kontrollü bir bütünlük sağlar.":"Glued or fleece-backed edge bands produced from natural and industrial veneers, excluding burls, create a controlled continuity with the panel surface."}</p><dl className="spec-table"><div><dt>{tr?"Standart genişlik":"Standard width"}</dt><dd>22 mm · 45 mm</dd></div><div><dt>{tr?"Tela destekli rulo":"Fleece-backed roll"}</dt><dd>100 m</dd></div><div><dt>{tr?"Tutkallı rulo":"Pre-glued roll"}</dt><dd>50 m</dd></div><div><dt>{tr?"Talebe bağlı genişlik":"On-request width"}</dt><dd>12–200 mm</dd></div></dl></div></div></section>}
const galleryImages=["AFRAMOSIA.jpg","usa_ceviz.jpg","zebranoo.jpg","a3_harelimese.jpg","c22_abanozkok.jpg","Dogal-Teak.jpg","dumanli-mese.jpg"];
function Gallery({locale}:{locale:Locale}){const tr=locale==="tr";return <section className="editorial"><div className="section-head"><div><span className="eyebrow">{tr?"KÜRATÖRLÜ KATALOG SEÇKİSİ":"CURATED CATALOGUE SELECTION"}</span><h2>{tr?"Damar, ton ve dokunun gerçek seçkisi.":"A true study of grain, tone and texture."}</h2></div><p>{tr?"Çalışırlar ürün kataloğundan seçilen yüzeyleri, malzemenin doğal ayrıntısını koruyan gerçek görsellerle inceleyin.":"Explore surfaces selected from the Çalışırlar catalogue through genuine imagery preserving their natural detail."}</p></div><div className="gallery-grid">{galleryImages.map((image,index)=><div className="gallery-item" key={image}><Image src={`/images/products/${image}`} fill sizes="(max-width:760px) 100vw, 60vw" alt={`${tr?"Çalışırlar ahşap yüzey kataloğu":"Çalışırlar wood surface catalogue"} ${index+1}`}/><span>{tr?"Malzeme":"Material"} 0{index+1}</span></div>)}</div></section>}
function Documents({locale}:{locale:Locale}){const tr=locale==="tr";const docs=tr?[["Kurumsal Takdir","İzmir ticaret ve vergi performansına ilişkin belge"],["Sanayi Başarısı","Ege Bölgesi Sanayi Odası"],["Marka & Kalite","Türk Patent ve kalite yönetimi referansları"]]:[["Corporate Recognition","İzmir trade and tax performance document"],["Industrial Achievement","Aegean Region Chamber of Industry"],["Brand & Quality","Turkish Patent and quality-management references"]];return <section className="editorial"><div className="cards-3">{docs.map(([title,body],index)=><article className="info-card" key={title}><span className="eyebrow">0{index+1}</span><div><h3>{title}</h3><p>{body}</p></div><span className="form-note">{tr?"Belge kopyaları ve güncel geçerlilik bilgileri talep halinde paylaşılır.":"Document copies and current validity information are available on request."}</span></article>)}</div></section>}
function Contact({locale}:{locale:Locale}){const tr=locale==="tr";return <section className="editorial"><div className="contact-grid"><div className="contact-details"><section><span className="eyebrow">{tr?"MERKEZ OFİS":"HEAD OFFICE"}</span><h3>Çalışırlar Orman Ürünleri</h3><p>{companyContact.headOffice}</p>{companyContact.headPhones.map(p=><a key={p} href={`tel:${p.replace(/\D/g,"")}`}>{p}</a>)}</section><section><span className="eyebrow">{tr?"FABRİKA":"FACTORY"}</span><h3>Torbalı · İzmir</h3><p>{companyContact.factory}</p>{companyContact.factoryPhones.map(p=><a key={p} href={`tel:${p.replace(/\D/g,"").slice(0,12)}`}>{p}</a>)}</section><a className="text-link" href={`mailto:${companyContact.email}`}>{companyContact.email}<Arrow/></a></div><ContactForm locale={locale}/></div></section>}
